### ISSUE TITLE
Failed to load in IE

### ISSUE THREAD

**Issue by ipip2005** [Teamwork/visual-dom-diff#3]
[This extra comma](https://github.com/Teamwork/visual-dom-diff/blob/1372785c072d675741ea1fb51d4b135533e8efdc/src/config.ts#L110) and some other syntax errors are causing script loading errors in IE. We're not able to use the library on IE browser.

![image](https://user-images.githubusercontent.com/7711735/67133243-d5883880-f1c0-11e9-8a20-606deec72f85.png)

When loading demo page on IE locally, also seen this error
![image](https://user-images.githubusercontent.com/7711735/67133746-1d0fc400-f1c3-11e9-8a9e-e067f0fd17f1.png)

**Comment by gkubisa** [comment]
This module is published as ES 2018 (see [tsconfig.json](https://github.com/Teamwork/visual-dom-diff/blob/1372785c072d675741ea1fb51d4b135533e8efdc/tsconfig.json#L3)), so you'll need to transpile it yourself to ES5, so that it would work in IE - that extra comma is just one example of the new syntax not supported by IE. The demo app transpiles the module using [webpack](https://github.com/Teamwork/visual-dom-diff/blob/1372785c072d675741ea1fb51d4b135533e8efdc/webpack.config.js#L17) and [babel](https://github.com/Teamwork/visual-dom-diff/blob/1372785c072d675741ea1fb51d4b135533e8efdc/babel.config.js), and it did work in IE11 the last time I checked.

If you use webpack, remember that it does not transpile `node_modules` by default, so you'll need to "include" `__dirname + '/node_modules/visual-dom-diff/'` in `babel-loader` in your [webpack config](https://github.com/Teamwork/visual-dom-diff/blob/1372785c072d675741ea1fb51d4b135533e8efdc/webpack.config.js#L16).

**Comment by ipip2005** [comment]
@gkubisa Thanks for explanation! Is it possible to publish this module in other (multiple) targets? It doesn't need to change es2018, just add another one that works on IE by default? Maybe the default entry is es2018 but we can still import from a different lib folder to load IE compatible modules?

I'm working in a mono repo where it's extremely hard to modify webpack configuration due to the fact how our tool chain is used.

**Comment by gkubisa** [comment]
It would be technically possible to publish for multiple targets, however, I don't want to do it because it would add complexity just for the sake of supporting IE11 by default, while a [good general solution](https://github.com/babel/babel-loader/issues/171) already exists.

> I'm working in a mono repo where it's extremely hard to modify webpack configuration due to the fact how our tool chain is used.

We're in a similar situation now with one of our older products and are currently updating our build system to support ES6 in node_modules. It is very hard but it also seems inevitable, as the number of ES6-only modules is bound to increase over time.

If updating the build system is not an option for you at this time, a quick workaround could be to set up a new module which simply depends on `visual-dom-diff`, transpiles it and publishes as ES5.

**Comment by gkubisa** [comment]
To be honest, I didn't make any serious effort to support IE11, as we ended up using this lib in nodejs with [jsdom](https://github.com/jsdom/jsdom). IE11 support would certainly be nice to have and while I don't currently have time to implement it, I will accept a PR.

Here's what I think needs to be done:

- provide a fallback for [getAttributeNames](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNames) - to avoid the need for a polyfill
- stop using [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) - to avoid the need for a polyfill
- stop using `for of` loops - to avoid code bloat and performance impact of the transpiled version
- discover and avoid any other features that require polyfills - I don't think there are any more
- change the TypeScript compilation target to ES5
- create a [benchmark](https://github.com/bestiejs/benchmark.js/) - to ensure that performance is not negatively affected by the changes - I care mostly about v8/nodejs.

Would you like to do this work, @ipip2005 ? Let me know, if you have any questions or suggestions regarding the above.

**Comment by ipip2005** [comment]
I'm not familiar with some areas but i would like to have a try.
When I'm playing with the library locally, I encountered some issues after I pull latest master and finished `rush install`

1. When I run `npm run build`. It failed at prettier step:
![image](https://user-images.githubusercontent.com/7711735/67924246-581fd900-fb6d-11e9-8f22-b40d3abffa8c.png)

2. When I run `npm run start`. The demo page launches but there is not content in the "Diff" box.
![image](https://user-images.githubusercontent.com/7711735/67924281-71288a00-fb6d-11e9-989e-fad470754f2d.png)

Below is my node and npm versions:
![image](https://user-images.githubusercontent.com/7711735/67924154-1000b680-fb6d-11e9-9959-5d9b8f63f5b2.png)

Is it same for you or I missed something?

**Comment by gkubisa** [comment]
It looks like a problem with the patterns passed to `prettier` on Windows. I think they might need to be updated to use double quotes `"` instead of single quotes `'`, see https://github.com/lbryio/lbry-wunderbot/issues/154.

**Comment by ipip2005** [comment]
@gkubisa 
I fixed the quote issue together with another few issues so finally this repo works for me on Windows.
I sent a PR to fix the tooling issues
https://github.com/Teamwork/visual-dom-diff/pull/4

I'll start tackling around the IE issues

**Comment by ipip2005** [comment]
@gkubisa I've sent [a PR](https://github.com/Teamwork/visual-dom-diff/pull/5) and tested the demo page now works with IE browser.
One TODO left from your list is benchmark. Although I don't anticipate a perf regression on v8/nodejs, I will try to make a perf comparison.

**Comment by ipip2005** [comment]
I'm doing some benchmark stuff, but I'm not sure if I should integrate benchmark to the project, and how.
So right now I'm just putting numbers

I took some sample data from `diff.test.ts` unit tests and executed benchmark in node environment
This is the data for master branch
![image](https://user-images.githubusercontent.com/7711735/68165458-5b6fe780-ff14-11e9-91f5-98b402a4f157.png)

And this is the data for my ie-support branch
![image](https://user-images.githubusercontent.com/7711735/68165363-1946a600-ff14-11e9-8990-a4781a8a9dc1.png)

The numbers are quite close

**Comment by gkubisa** [comment]
Nice one! Please add the benchmark to the `./scripts` directory.

**Comment by ipip2005** [comment]
Added benchmark to `./scripts` and added `npm run benchmark` to invoke t quickly

**Comment by gkubisa** [comment]
Thanks for your help with fixing it @ipip2005 . The changes are published in 0.7.2.
